### ISSUE TITLE
Calculate Play Rate not working

### ISSUE THREAD

**Issue by benjdarling** [Avindr/Strider-UE4-Issue-Tracking#12]
version: 4.25
strider version: 1.8

"calculate play rate" node is returning between min rate and 1 (give or take a bit of floating point noise)

Happening just while using it typically in anim bp event graph
Have tried manually feeding it different values and even setting the max rate to 10, same result, caps at 0.999/1.0001 etc.

**Comment by Avindr** [comment]
I'll look into it. Thankyou

**Comment by Avindr** [comment]
Unfortunately I can't reproduce this. As shown in the below image the output from this node is above 1.0 sitting at the set 'MaxPlayRate' of 1.1. This is in the example project without any changes.

The function is extremely simple and after doing some checks it appears impossible for it to clamp at 1 unless:
1. Playback Weight is set to 0
2. Your MaxPlayRate is set to 1
3. Your input 'TotalSpeedScale' does not exceed 1

![image](https://user-images.githubusercontent.com/29056263/114955658-82b83b80-9ea0-11eb-94bd-39f600788b35.png)
