### ISSUE TITLE
Orientation Warping with non standard up axis?

### ISSUE THREAD

**Issue by jswigart** [Avindr/Strider-UE4-Issue-Tracking#14]
Something to do with my content is not working right with Strider, despite setting a Y or -Y up axis. I hope there is a way to fix it in strider before telling the animators they need to alter the skeleton and animations, etc.

This is Unreal 4.26.1, latest Strider.

The issue is that it appears a roll is being applied to the spine bones rather than the rotation going along the Y, as configured.

Here is a sample project with the issue. I have extracted a minimal set of assets and copied the example anim bp and changed settings to our anims on our character.

![twist1](https://user-images.githubusercontent.com/4065267/113046829-22b65b00-9166-11eb-8847-65e7271b3d7c.JPG)

If you open the ABP_Busted animation blueprint you will see the issue right away, as I have set the default values of the preview variables to demonstrate it

https://drive.google.com/file/d/18uSC63K4XeRRZT21pfHFqqSRaio875Ti/view?usp=sharing

**Comment by jswigart** [comment]
For whatever reason, our bones are oriented as such in UE4.

![twist3](https://user-images.githubusercontent.com/4065267/113047293-c0aa2580-9166-11eb-9275-23687f067a1c.JPG)
![twist4](https://user-images.githubusercontent.com/4065267/113047296-c142bc00-9166-11eb-8f87-2af6c2e9cb77.JPG)

Which is probably related to the issue, however with a configurable up axis, I had expected to be able to compensate for this on the strider node.

**Comment by jswigart** [comment]
The wierd thing, is that +Y or -Y Up is what Strider needs to rotate the whole model properly off the root, however, the spine bones get more of a roll rather than yaw, which then makes me think there are assumptions about the up axis with regards to the root that aren't holding true for the other bones.

I suspect it has something to do with the local rotation on our root bone, which I'm not sure why it is there. I am talking to our animators about it.

**Comment by Avindr** [comment]
Hi,

I'll look into it and see what I can do.

I did design Strider to compensate for a lot of different skeleton setups
but from time to time a new edge case pops up that I wasn't aware of. This
may be one of those cases and I'll investigate.

Regards,

Ken Claassen

**Comment by jswigart** [comment]
Apparently it wasn't difficult for the animators to get me a version of the assets without the root bone rotation, so as a test we removed it, and sure enough that's what the issue was. Looking at the code it makes sense, bc in order to compensate for the rotation of the root bone I had to use a different up axis, and using that again on the bone chain threw it out of wack. Not sure if you want to account for this possibility, but that was the issue.

**Comment by Avindr** [comment]
Thanks for the update.

I still might look into it and see if it's worth implementing something.

Cheers.

**Comment by jswigart** [comment]
A related issue

So our animators removed the orientation from the root bone in the animations, but apparently there is still orientation on the root bone of the skeleton, which causes a wierd issue with the SlopeWarp node, due to the calculation of IKRootOffset that includes the root bone rotation. I verified this was the issue by doing a temporary Transforms[0].SetRotation(FQuat::Identity); on the Transforms array in FAnimNode_SlopeWarp::InitializeBoneReferences to clear the root bone rotation, and the slope warp started working as expected.

I don't think this particular problem reproduces with the linked project above, so if you want me to set up another test project with this I can, but I'm just going to get the animators to fix it in the skeleton. Probably all kinds of stuff is going to have issues with awkward stuff like that.

**Comment by jswigart** [comment]
Broken
![slopewarp_broken](https://user-images.githubusercontent.com/4065267/113751455-96f67e80-96d1-11eb-800b-80211cf64e02.gif)

Working
![slopewarp_working](https://user-images.githubusercontent.com/4065267/113751475-99f16f00-96d1-11eb-828f-32d27b34966c.gif)

**Comment by Avindr** [comment]
Hi Jeremy,

Thanks for the info. I think there may be a bug in the current available
version relating to the IKRootOffset calculation. I will be deploying a
small update for Strider next week sometime so hopefully this resolves the
issue.

Regards,

Ken Claassen

**Comment by jswigart** [comment]
Ok great. If I could suggest one more minor change in an update that gives users a bit more flexibility in their blueprint, it would be to change the meta on the warp nodes for any properties currently set to always show pin, to show pin by default. This doesn't change the default usage of those properties but allows users to use the property binding for those properties to reduce blueprint clutter.

**Comment by jswigart** [comment]
For example

![image](https://user-images.githubusercontent.com/4065267/114205740-4032b400-9920-11eb-81fe-366df2330f86.png)

Which gives you the option to reduce blueprint connections/nodes using the binding stuff

![image](https://user-images.githubusercontent.com/4065267/114205915-6a847180-9920-11eb-8993-cc1b3eec7655.png)

**Comment by Avindr** [comment]
Sure no problem I can do that.

**Comment by Avindr** [comment]
All inputs now support binding instead of pins as well now. This will come soon with v1.9.

The slow warping issue should also be resolved in v1.9 but if not we can open this issue again.
