### ISSUE TITLE
Crash when browsing animations (caused by FootLockTimer.cpp)

### ISSUE THREAD

**Issue by DexGrimGrin** [Avindr/Strider-UE4-Issue-Tracking#21]
Unreal engine crashes consistently when opening animations.

According to the crash report:
Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000000
UnrealEditor_Strider!UAnimNotify_FootLockTimer::Notify()
[...Strider\Source\Strider\Private\Objects\AnimNotifies\AnimNotify_FootLockTimer.cpp:18]

I assume that means line 18 which is:
	if(UFootLockManager* FootLockManager = Cast<UFootLockManager>(MeshComp->GetOwner()->GetComponentByClass(UFootLockManager::StaticClass())))

It seems something like a 1 in 5 chance that opening an animation will crash the editor.
I cannot find any pattern to the crashes. (animations without any notifies crash just as much as those with them.

![Untitled](https://github.com/Avindr/Strider-UE4-Issue-Tracking/assets/142746994/037572fd-466e-4ec6-80f1-2d977fa5ef83)

**Comment by Avindr** [comment]
Thanks for the info. While I haven't been able to reproduce it on my end, I've added additional safety checks in the anim notify so that this should not occur. 

Update has already been pushed to github and will be available on UE Marketplace within the next few days.
