### ISSUE TITLE
slope warp issue

### ISSUE THREAD

**Issue by redtankbai** [Avindr/Strider-UE4-Issue-Tracking#3]
hi, thanks for make this tool!

i met some issue when using slope warp:
i have a character set up with root -> foot ik root -> foot ik left and foot ik right, which is pretty normal, but the only difference is both "root" and "foot ik root" has  -Y upward and +Z forward setup. the standard unreal character "Mannequin" has +Z upward and +Y forward. and i got wrong result with my character, looks like "foot ik root" been rotate towards wrong direction like show in pic:
[https://imgur.com/WoglkQk](https://imgur.com/WoglkQk)

so i'd like to know if any idea to solve this? or you may like to update tool to make it more flexible for this case? thx!

**Comment by redtankbai** [comment]
PS: tried same slope warp setting with standard Mannequin character, and working very well, so pretty sure it's cause by axis different

**Comment by redtankbai** [comment]
PPS: in my wrong result, not only foot ik root rotation issue, but also hips movement issue, hips will been pull towards ground with large distance, so even i fixed foot ik rotation with transform bone follow slope warp node, still got wrong hips position cause animation unusable

**Comment by Avindr** [comment]
Hi, 

For slope warping to work correctly, it is a requirement that the IKRoot is set up with the correct / standard axis and orientation. This is because slope warping rotates the root to conform to the slope. Building in an offset may negatively impact sloped animations that already have IKRoot rotation for slope.

I will look into the possibility of providing some kind of offset that doesn't negatively affect that. However, it is better to have the IKRoot axis set up in the standard orientation.

**Comment by redtankbai** [comment]
the reason we build root and ik orientation in that way is because we creat rig in Maya and animate in MotionBuilder, both of software is Y up, but Unreal4 is Z up

i believe our pipeline is pretty common as many other studios so it will help your tool become more popular if this issue got solved

thanks and looking for your good news!

**Comment by Avindr** [comment]
I'm made some changes in the code to accommodate this without having to additional exposed variables. 

By any chance would it be possible for you to send me an example model with the IKRoot Y-up so I can test if it is working correctly in this case?

**Comment by Avindr** [comment]
Changes have been made to allow for off-axis IkRoot nodes. These changes are available in Strider v1.3 which has been submitted and should be available soon on the UE4 marketplace.
