### ISSUE TITLE
Slope Warp Foot offset issue

### ISSUE THREAD

**Issue by redtankbai** [Avindr/Strider-UE4-Issue-Tracking#4]
![image](https://user-images.githubusercontent.com/35935360/93407497-5da71000-f860-11ea-801f-f129ae172e98.png)
 as shown in this image, can see pose balance been broken when on slope

the reason i think is because slope warp only rotate ik root bone but not move it, and foot mesh hes height, then we got this issue

to solve it, my idea is concern about height of foot mesh, can get it by foot bone position or user input, and then move foot ik root bone align slope, to keep foot joint in it's original verticle place, like this:
![image](https://user-images.githubusercontent.com/35935360/93407893-3c92ef00-f861-11ea-9743-f0c0fd9f3237.png)

or you may have even better idea :)

**Comment by redtankbai** [comment]
may also need adjust hips position to avoid crouch legs

**Comment by Avindr** [comment]
The foot IK Root shouldn't need to be moved. This looks instead like the hips are shifting up the slope. I recommend turning on the slope warp debugging (and wire-frame rendering) to see exactly what is happening with the hips and that might give more insight into this. 

a.AnimNode.Warp.Slope.Debug = 3

Also can you show me a screenshot of the node settings.

**Comment by redtankbai** [comment]
debug inform:
![image](https://user-images.githubusercontent.com/35935360/93414824-19bc0700-f870-11ea-91c6-bb676b0dfd1b.png)
![image](https://user-images.githubusercontent.com/35935360/93414837-22acd880-f870-11ea-82c7-bd70708f52e2.png)
![image](https://user-images.githubusercontent.com/35935360/93414897-4a03a580-f870-11ea-823a-7a81158b71ff.png)
![image](https://user-images.githubusercontent.com/35935360/93414931-63a4ed00-f870-11ea-87d6-6b52a2299473.png)
![image](https://user-images.githubusercontent.com/35935360/93414999-86370600-f870-11ea-989b-84bfce9aa2e5.png)

maybe it's not very clear to show hips before and after position, but i can see it's on same verticale line

**Comment by Avindr** [comment]
Thanks I'll look into this and get back to you :)

**Comment by Avindr** [comment]
I've had a look into this. It seems to occur due to the offset of the ankle to the ground, where the ankle gets pushed out to the side a bit. 

Shifting the IKRoot pivot up the slope will have un-desirable effects. I will instead add some hip adjustment so that the hips are pushed back over the feet. 

This will be available in the next update to Strider

**Comment by Avindr** [comment]
A feature has been added in Strider v1.3 to overcome this. A new setting on the Stride Warp node called 'Slope Roll Compensation'. Please see [Section 7.4 of the User Manual](https://docs.google.com/document/d/10BXxS6j0EUt47INlHjCrMgagHgeVPVONR0I5LCWTNMw/edit#heading=h.hirr8vaany1k) for details. 

Strider v1.3 has been submitted for approval and should be available soon on the marketplace.
