### ISSUE TITLE
Lack of additional 'hip adjustment' bones in Stride Warp

### ISSUE THREAD

**Issue by herr-edgy** [Avindr/Strider-UE4-Issue-Tracking#6]
The great sword anim pack from marketplace is set up so that the sword has to be attached to the ik_hand_r bone. Meaning the ik_hand_r bone is animated to be on the back of the character while unequipped, and close to the hands for combat animations.
When I use the Stride Warp, the pelvis hierarchy will be adjusted downwards, but the ik_hand_r bone will remain where it was, making the sword float.

[Image on gyazo](https://i.gyazo.com/b5f9c6457d73c5e374af45c5bfdafb05.png)

This happens because the ik_hand_r bone is outside of the pelvis hierarchy.

I tried appending a 2nd Stride Warp node, and using the ik_hand_r bone as the hip bone so that it gets lowered instead and it works to a degree, but not completely. I think this could fixed well if you could just have an array for additional bone hierarchies.

This might apply to other warps as well, but I haven't tried them out yet.

**Comment by Avindr** [comment]
I will add this functionality in the next update. It may affect some of the other nodes as well so I'll make sure it works with all of them.

Cheers

**Comment by Avindr** [comment]
I have added this functionality to Stride and Slope warping nodes for v1.6 (submitted) to shift any additionally listed bones up and down with the hips (This list is located in an 'AdvancedDisplay' dropdown in the details panel). 

A similar treatment will be applied to the other nodes soon but their method of adjustment is not necessarily so simple. I will leave this issue open in the meantime.

**Comment by herr-edgy** [comment]
Great, much appreciated

**Comment by Avindr** [comment]
Update v1.7 (submitted) brings a similar solution for Orientation and bank warping nodes.

**Comment by Avindr** [comment]
Revisiting the status of this issue. It appears as if it has been completed. 

Acceleration Warp Node does not modify the character root or hip height so it does not require the same treatment.
