### ISSUE TITLE
Enum definitions in EStriderEnumerations.h pollute global namespace

### ISSUE THREAD

**Issue by JHuculak** [Avindr/Strider-UE4-Issue-Tracking#7]
There are two ways to declare enums in UE4:
```
enum ESomeEnum
{
...
}
```
and
```
enum class ESomeEnum : uint8
{
...
}
```

[This StackOverflow post](https://stackoverflow.com/questions/18335861/why-is-enum-class-preferred-over-plain-enum) does a good job of explaining the differences between them; the long and short is that the way these enums are currently declared (method 1) ends up dumping those enum values into the enclosing namespace -- which, because one isn't defined, is the _global_ namespace.

This ends up interfering with enum resolution & lookup in the Unreal Engine; specifically, when we try to look up an enum that doesn't exist, we try to search by an FName of `None`. Typically this will result in the enum not being found, but because ESlopeRoleCompensation is defined as a naked enum without an enclosing namespace, the name `None` actually ends up mapping to this enum. This results in various undesired behaviors; for example, `FNumericProperty::ImportText_Internal` will always set the property value to 0 (instead of leaving it untouched) if it is provided with an alphabetical string that does not correspond directly to an enum value because of this mapping.

Recommended resolution:

Change all enum definitions in `EStriderEnumerations.h` to be `enum class`es.

**Comment by Avindr** [comment]
Thanks for the long explanation. The error is more of an overlooked typo really. I always intend to use enum class. 

This will be fixed in the next update

**Comment by Avindr** [comment]
Strider v1.6 has been submitted to the marketplace and should be available within a day or two. v1.6 resolves this issue.
