### ISSUE TITLE
Orientation warping stutter when moving at 45degree angles 

### ISSUE THREAD

**Issue by Avindr** [Avindr/Strider-UE4-Issue-Tracking#9]
Report of the orientation warping node stuttering at 45degree angles of movement.

- Required reproduction
- Awaiting further information

**Comment by Koleshy** [comment]
This happens sometimes when moving W + A or W + D and mouse (there may be an intersection problem im not sure)

Something similar is happening with the Bank Warp it sometimes vibrate in a certain point when move W + A or W + D and moving mouse)

*** I reproduced all these test in your project example. I hope you check this and the other nodes as soon possible thanks. (also check inverse S + A or S + D)

**Comment by Avindr** [comment]
It took a while to reproduce this issue for me in the example project and it was a lot more subtle for me than you described it. However, this is probably due to other differences in setup / frame rate etc. 

Fortunately the issue is not with the Strider node itself but rather one of the utility blueprint function library nodes which wasn't clamping / wrapping the direction angle properly between -180 to 180 degrees. This has been fixed for the next build which I will upload very soon after a bit more more testing.
